# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27fcff9152351161cc96443dc6d95fc56aefe46516e67ffdfe125114a351e4f9817d29f6a954b0a43257d53da4238acc088b225fdffead20a8fca4e8554ef570

test:
  secret_key_base: 8f52ffa8e2de721c62f1ad5c718b9ccea7890053ca96ee389e086ca893962ba18b57b8eda4e7cfd4a201e5aaba80b97594bde122c1477d13b67f51bedd0f1f60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
